[package]
name = "CorruptusConscribo"
version = "0.1.0"
authors = ["Harrison Barker <harrison@thebarkers.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"